apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan-server
  labels:
    app: infinispan-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinispan-server
  template:
    metadata:
      labels:
        app: infinispan-server
    spec:
      containers:
      - name: infinispan-server
        image: infinispan/server
        env:
          - name: USER
            value: admin
          - name: PASS
            value: admin
        ports:
        - containerPort: 11222

---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-server
spec:
  selector:
    app: infinispan-server
  type: LoadBalancer
  ports:
  - port: 11222
    targetPort: 11222
